version: "3.9"

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.132.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - GRPC_FILE_EXPORTER_ENDPOINT=0.0.0.0:4317
      - HTTP_FILE_EXPORTER_ENDPOINT=0.0.0.0:4318
    volumes:
      - ../data/traces:/data:rw
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
